import {Roboto} from "next/font/google";
import {Header} from "@/components/shared/Header";
import {Footer} from "@/components/shared/Footer";
import "@/sass/globals.sass";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

const roboto = Roboto({
    weight: ["400", "700"],
    style: ["normal", "italic"],
    subsets: ["latin"],
})

// export const metadata: Metadata = {
//     title: "Future World",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
